Repository crowdsecurity/helm-charts, pull requests merged in 2024-06, with the labels that each got.

#169 Middleware API Version traefik.io/v1alpha1
  charts/crowdsec-traefik-bouncer/templates/middleware.yaml
Labels: area/configuration, kind/fix

#168 Add option to disable varlog hostPath
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/agent

#167 Add annotations to LAPI deploy, Agent daemonset and secretTemplate for certificates
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/templates/tls/agent-certificate.yaml
  charts/crowdsec/templates/tls/bouncer-certificate.yaml
  charts/crowdsec/templates/tls/lapi-certificate.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#171 Update crowdsec v1.6.2
  charts/crowdsec/Chart.yaml
Labels: kind/dependencies, needs/area

#172 bump version for release 0.11
  charts/crowdsec/Chart.yaml
Labels: kind/enhancement, needs/area
