Repository crowdsecurity/helm-charts, pull requests merged in 2024-04, with the labels that each got.

#148 Add podLabels & podAnnotations for crowdsec chart
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/values.yaml
Labels: needs/kind, needs/area

#154 fix doc + add forgotten values param
  charts/crowdsec/values.yaml
Labels: area/configuration, kind/chore

#155 Reduce governance schedule frequency
  .github/workflows/governance-bot.yaml
Labels: kind/enhancement, triage/accepted, area/configuration

#112 Support for LAPI High availability
  charts/crowdsec/Chart.yaml
  charts/crowdsec/README.md
  charts/crowdsec/templates/_helpers.tpl
  charts/crowdsec/templates/lapi-configmap.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/templates/lapi-secrets.yaml
  charts/crowdsec/values.schema.json
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/local-api

#157 Add lifecycle support for LAPI
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#160 Add support for custom tls issuer
  charts/crowdsec/templates/tls/agent-certificate.yaml
  charts/crowdsec/templates/tls/bouncer-certificate.yaml
  charts/crowdsec/templates/tls/ca-certificate.yaml
  charts/crowdsec/templates/tls/ca-issuer.yaml
  charts/crowdsec/templates/tls/crowdsec-clusterIssuer.yaml
  charts/crowdsec/templates/tls/lapi-certificate.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#159 Update to v1.6.1
  charts/crowdsec/Chart.yaml
Labels: kind/enhancement, area/configuration

#145 revamp README
  README.md
Labels: needs/kind, area/configuration

#162 set higher resources limits
  charts/crowdsec/values.yaml
Labels: area/configuration, kind/fix

#163 add lapi resources
  charts/crowdsec/values.yaml
Labels: area/configuration, kind/fix
