Repository crowdsecurity/helm-charts, pull requests merged in 2024-11, with the labels that each got.

#189 add appsec in crowdsec chart
  charts/crowdsec/README.md
  charts/crowdsec/ci/crowdsec-values.yaml
  charts/crowdsec/templates/NOTES.txt
  charts/crowdsec/templates/appsec-configmap.yaml
  charts/crowdsec/templates/appsec-deployment.yaml
  charts/crowdsec/templates/appsec-service.yaml
  charts/crowdsec/templates/appsec-serviceMonitor.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/templates/lapi-secrets.yaml
  charts/crowdsec/templates/tests/test_appsec_up.yaml
  charts/crowdsec/values.yaml
Labels: area/configuration, kind/feature

#197 feat: improve capi registration
  charts/crowdsec/README.md
  charts/crowdsec/files/docker-start-custom.sh
  charts/crowdsec/templates/_helpers.tpl
  charts/crowdsec/templates/capi-credentials-secrets.yaml
  charts/crowdsec/templates/capi-register-job.yaml
  charts/crowdsec/templates/docker-start-configmap.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/templates/role.yaml
  charts/crowdsec/templates/rolebinding.yaml
  charts/crowdsec/templates/serviceaccount.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, needs/area

#198 bump chart version to 0.14.0
  charts/crowdsec/Chart.yaml
Labels: needs/kind, needs/area

#201 Bump chart to 0.14.1
  charts/crowdsec/Chart.yaml
Labels: needs/kind, needs/area

#207 bump chart and crowdsec versions
  charts/crowdsec/Chart.yaml
Labels: needs/kind, needs/area
