Repository crowdsecurity/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#123 Fix dashboard init trying to ask for confirmation when overwriting existing db
  charts/crowdsec/templates/lapi-deployment.yaml
Labels: area/local-api, kind/fix

#188 Add values to add extraVolumes to lapi and agent
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#193 Bump crowdsec to 1.6.3 and chart to 0.13.0
  charts/crowdsec/Chart.yaml
Labels: kind/chore, needs/area
