Repository crowdsecurity/helm-charts, pull requests merged in 2024-12, with the labels that each got.

#210 fix(crowdsec): update readme
  .github/workflows/release.yaml
  charts/crowdsec/Chart.yaml
  charts/crowdsec/README.md.gotmpl
Labels: area/configuration, kind/fix

#209 Change agent username/password into auto_registration
  charts/crowdsec/templates/_helpers.tpl
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/agent-deployment.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/templates/secrets.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/agent

#208 Appsec high availability using replicas
  charts/crowdsec/ci/crowdsec-values.yaml
  charts/crowdsec/templates/_helpers.tpl
  charts/crowdsec/templates/appsec-deployment.yaml
  charts/crowdsec/templates/lapi-secrets.yaml
  charts/crowdsec/templates/tests/test_agent_up.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#215 bump crowdsec chart version
  charts/crowdsec/Chart.yaml
Labels: needs/kind, needs/area

#218 feat(crowdsec): add example for appsec (WAF) with wordpress
  examples/crowdsec/crowdsec-with-appsec-simple/README.md
  examples/crowdsec/crowdsec-with-appsec-simple/crowdsec-values.yaml
  examples/crowdsec/crowdsec-with-appsec-simple/ingress-nginx-bouncer-values.yaml
  examples/crowdsec/crowdsec-with-appsec-simple/wp-values.yaml
Labels: needs/kind, needs/area

#216 Added kubernetes audit datasource to values.schema.json
  charts/crowdsec/values.schema.json
Labels: area/agent, kind/fix
