Repository crowdsecurity/helm-charts, pull requests merged in 2025-01, with the labels that each got.

#223 feat(crowdsec): install lapi and agent separatly
  charts/crowdsec-traefik-bouncer/templates/deployment.yaml
  charts/crowdsec-traefik-bouncer/templates/middleware.yaml
  charts/crowdsec-traefik-bouncer/templates/service.yaml
  charts/crowdsec/ci/crowdsec-values.yaml
  charts/crowdsec/templates/NOTES.txt
  charts/crowdsec/templates/_helpers.tpl
  charts/crowdsec/templates/acquis-configmap.yaml
  charts/crowdsec/templates/agent-configmap.yaml
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/agent-deployment.yaml
  charts/crowdsec/templates/agent-persistentVolume.yaml
  charts/crowdsec/templates/agent-service.yaml
  charts/crowdsec/templates/agent-serviceMonitor.yaml
  charts/crowdsec/templates/appsec-configmap.yaml
  charts/crowdsec/templates/appsec-deployment.yaml
  charts/crowdsec/templates/appsec-service.yaml
  charts/crowdsec/templates/appsec-serviceMonitor.yaml
  charts/crowdsec/templates/capi-credentials-secrets.yaml
  charts/crowdsec/templates/capi-register-job.yaml
  charts/crowdsec/templates/lapi-configmap.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/templates/lapi-ingress.yaml
  charts/crowdsec/templates/lapi-persistentVolume.yaml
  charts/crowdsec/templates/lapi-secrets.yaml
  charts/crowdsec/templates/lapi-service.yaml
  charts/crowdsec/templates/lapi-serviceMonitor.yaml
  charts/crowdsec/templates/metabase-ingress.yaml
  charts/crowdsec/templates/role.yaml
  charts/crowdsec/templates/rolebinding.yaml
  charts/crowdsec/templates/serviceaccount.yaml
  charts/crowdsec/templates/tests/test_agent_up.yaml
  charts/crowdsec/templates/tests/test_appsec_up.yaml
  charts/crowdsec/templates/tests/test_lapi_up.yaml
  charts/crowdsec/templates/tls/agent-certificate.yaml
  charts/crowdsec/templates/tls/bouncer-certificate.yaml
  charts/crowdsec/templates/tls/ca-certificate.yaml
  charts/crowdsec/templates/tls/ca-issuer.yaml
  charts/crowdsec/templates/tls/crowdsec-clusterIssuer.yaml
  charts/crowdsec/templates/tls/lapi-certificate.yaml
  charts/crowdsec/values.schema.json
  charts/crowdsec/values.yaml
  charts/helloworld/templates/deployment.yaml
  charts/helloworld/templates/hpa.yaml
  charts/helloworld/templates/ingress.yaml
  charts/helloworld/templates/service.yaml
  charts/helloworld/templates/serviceaccount.yaml
  examples/crowdsec/crowdsec-separate-lapi-agent/README.md
  examples/crowdsec/crowdsec-separate-lapi-agent/crowdsec-agent-values.yaml
  examples/crowdsec/crowdsec-separate-lapi-agent/crowdsec-lapi-values.yaml
  examples/crowdsec/crowdsec-with-appsec-simple/crowdsec-values.yaml
Labels: area/configuration, kind/feature

#225 fix template quote
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/agent-deployment.yaml
Labels: area/configuration, kind/fix

#226 agent deployment: always set LAPI_HOST, LAPI_PORT
  charts/crowdsec/templates/agent-daemonSet.yaml
Labels: kind/fix, needs/area

#220 fix(crowdsec): Prevent empty annotation error for cert manifests
  charts/crowdsec/templates/tls/agent-certificate.yaml
  charts/crowdsec/templates/tls/bouncer-certificate.yaml
Labels: area/configuration, kind/fix

#222 update appsec deployment to work with tls
  charts/crowdsec/templates/appsec-deployment.yaml
  charts/crowdsec/templates/tls/appsec-certificate.yaml
  charts/crowdsec/values.yaml
Labels: kind/fix, needs/area

#229 Bugfix: double command for agent container
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/agent-deployment.yaml
Labels: area/agent, kind/fix

#232 fix(crowdsec): Create capi-credentials secrets in pre-upgrade
  charts/crowdsec/templates/capi-credentials-secrets.yaml
Labels: area/configuration, kind/fix

#231 Activate auto registration token by default and update docs on authentication
  charts/crowdsec/README.md.gotmpl
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#235 fix(crowdsec): fix registrationToken templating
  charts/crowdsec/templates/_helpers.tpl
Labels: needs/kind, needs/area

#236 bump chart version; pin register job image tag; replace jq->yq
  charts/crowdsec/Chart.yaml
  charts/crowdsec/templates/capi-register-job.yaml
Labels: kind/fix, needs/area

#233 charts/crowdsec/values.schema: add rules for VictoriaLogs
  charts/crowdsec/values.schema.json
Labels: kind/enhancement, needs/area
