Repository crowdsecurity/helm-charts, pull requests merged in 2025-04, with the labels that each got.

#253 simpler capi-credential secret creation; fix issue with chart upgrade
  charts/crowdsec/templates/capi-credentials-secrets.yaml
  charts/crowdsec/templates/capi-register-job.yaml
  charts/crowdsec/templates/role.yaml
Labels: kind/fix, needs/area

#251 Added generated release notes to release workflow
  cr.yaml
Labels: kind/enhancement, area/configuration

#254 release 0.19.2
  charts/crowdsec/Chart.yaml
Labels: kind/chore, needs/area

#247 feat(capi-register-job): add custom labels to CAPI register pod
  charts/crowdsec/templates/capi-register-job.yaml
Labels: area/configuration, kind/feature
