Repository crowdsecurity/helm-charts, pull requests merged in 2025-05, with the labels that each got.

#265 Support external secret
  charts/crowdsec/templates/_helpers.tpl
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/agent-deployment.yaml
  charts/crowdsec/templates/appsec-deployment.yaml
  charts/crowdsec/templates/lapi-deployment.yaml
  charts/crowdsec/templates/lapi-secrets.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#264 Add support for PodMonitors and scraping metrics from PODs
  charts/crowdsec/templates/agent-podMonitor.yaml
  charts/crowdsec/templates/appsec-podMonitor.yaml
  charts/crowdsec/templates/lapi-podMonitor.yaml
  charts/crowdsec/values.yaml
Labels: kind/enhancement, area/configuration

#262 Fix podAnnotations in appsec deployment
  charts/crowdsec/templates/appsec-deployment.yaml
Labels: area/configuration, kind/fix

#263 Fix registration token being regenerated on redeploy
  charts/crowdsec/templates/_helpers.tpl
Labels: area/configuration, kind/fix

#267 allow custom config.yaml.local for agent and appsec pods
  charts/crowdsec/templates/agent-configmap.yaml
  charts/crowdsec/templates/agent-daemonSet.yaml
  charts/crowdsec/templates/agent-deployment.yaml
  charts/crowdsec/templates/appsec-configmap.yaml
  charts/crowdsec/templates/appsec-deployment.yaml
  charts/crowdsec/values.schema.json
  charts/crowdsec/values.yaml
Labels: kind/enhancement, needs/area
